package tab2xml.xmlconversion;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

import javax.xml.XMLConstants;
import javax.xml.transform.stream.StreamSource;
import javax.xml.validation.Schema;
import javax.xml.validation.SchemaFactory;
import javax.xml.validation.Validator;

import org.xml.sax.SAXException;

/**
 * Validation of XML output against the musicxml.xsd format.
 * 
 * @author amir
 */
public class ValidateXML {

    private File xsd;

    public ValidateXML(File xsd) {
	this.xsd = xsd;
    }

    /**
     * @param musicxmlxsd path to the musicxml.xsd
     * @param output      path to the XML generated by the Transformer
     * @return true if the output meets the musicxml.xsd criteria
     */
    public boolean validate(String output) {
	try {
	    SchemaFactory factory = SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI);
	    Schema schema = factory.newSchema(xsd);
	    Validator validator = schema.newValidator();
	    validator.validate(new StreamSource(new ByteArrayInputStream(output.getBytes(StandardCharsets.UTF_8))));
	} catch (IOException | SAXException e) {
	    System.out.println("Exception: " + e.getMessage());
	    e.printStackTrace();
	    return false;
	}
	return true;
    }
}
