package tab2xml.xmlconversion;

import java.io.File;
import java.io.IOException;
import java.nio.file.Path;

import javax.xml.XMLConstants;
import javax.xml.transform.stream.StreamSource;
import javax.xml.validation.Schema;
import javax.xml.validation.SchemaFactory;
import javax.xml.validation.Validator;

import org.xml.sax.SAXException;

/**
 * Validation of XML output against the musicxml.xsd format.
 * 
 * @author amir
 */
public class ValidateXML {

	private File xsd;

	public ValidateXML(File xsd) {
		this.xsd = xsd;
	}

	/**
	 * @param musicxmlxsd path to the musicxml.xsd
	 * @param output      path to the XML generated by the {@code Transformer}
	 * @return {@code true} if the output meets the musicxml.xsd criteria
	 */
	public boolean validate(Path output) {
		try {
			SchemaFactory factory = SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI);
			Schema schema = factory.newSchema(xsd);
			Validator validator = schema.newValidator();
			validator.validate(new StreamSource(output.toFile()));
		} catch (IOException | SAXException e) {
			System.out.println("Exception: " + e.getMessage());
			e.printStackTrace();
			return false;
		}
		return true;
	}
}
